version: '3'

# Zookeeper uses host ips for names, so add these entries to /etc/hosts on the host
#
# 127.0.0.1 broker-1
# 127.0.0.1 broker-2
# 127.0.0.1 broker-3
# 127.0.0.1 schema-registry

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    env_file: zookeeper.env
    ports: 
      - 2181:2181

  broker-1:
    image: confluentinc/cp-kafka:5.0.0
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: '1'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:9092'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    env_file: broker.env

  broker-2:
    image: confluentinc/cp-kafka:5.0.0
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: '2'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:9093'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    env_file: broker.env

  broker-3:
    image: confluentinc/cp-kafka:5.0.0
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: '3'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-3:9094'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    env_file: broker.env

  schema-registry:
    image: confluentinc/cp-schema-registry:5.0.0
    depends_on:
      - zookeeper
      - broker-1
      - broker-2
      - broker-3
    links:
      - zookeeper
      - broker-1
      - broker-2
      - broker-3
    ports:
      - 8083:8083
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: 'http://schema-registry:8083'
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      
  kafka-rest:
    image: confluentinc/cp-kafka-rest:5.0.0
    depends_on:
      - zookeeper
      - schema-registry
    links:
    - zookeeper
    - schema-registry
    ports:
      - 8082:8082
    environment:
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_HOST_NAME: http://localhost
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8083

